[package]
name = "piston_test"
version = "0.1.0"
authors = ["tomisoka <tomisokacz@gmail.com>"]

[dependencies]
piston_window = "0.64.0"
piston = "0.31.4"
pistoncore-glutin_window = "0.35.0"
piston2d-opengl_graphics = "0.42.0"
rand = "0.3.15"
